permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 路，漫漫走
  email: 1104243703@qq.com
  weibo: http://weibo.com/suxishui5201314
  github: http://github.com/Lance201314

# 站点信息
title: 路，漫漫走的博客 
description: 路，漫漫走的博客
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1

# disqus 设置
disqus:
  shortname: lance-zh
