permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

# 作者信息
author: 
  name: 路，漫漫走
  email: 1104243703@qq.com
  weibo: http://weibo.com/suxishui5201314
  github: http://github.com/Lance201314

# 站点信息
title: 路，漫漫走的博客 
description: 路，漫漫走的博客
rss_url: /pages/atom.xml
introduction: there's something we want to do

# avatar头像及Favicon
avatar: http://blog-github.5513a1499bc8c.d01.nanoyun.com/8435e5dde71190ef772420c0cc1b9d16fcfa60d5.png

# google analytics 设置
ga:
  id: UA-54767140-1

# disqus 设置
comments:
  provider: doushou
  duoshuo:
    short_name: Love_you_my_baby
